### ISSUE TITLE
Just a minor suggestion

### ISSUE THREAD

**Issue by gpk2000** [ouuan/CF-template#3]
Hey, I think the template is pretty cool. The only thing that is not so well looking is the debug part of the template so I also have the debug template in my code but I kept all the stuff inside a header and included it. I hope this improves your template look. Cheers :)

**Comment by ouuan** [comment]
That sounds good, but since I put them in the same line with other codes, and include needs one line, putting them in the template itself actually saves one line, thus looks better to me. I don't mind the template being a bit longer, because I use tabs to put them out of my sight, but the number of lines matters.

Also, it's more convenient to put everything in a single file for competitive programming.

**Comment by gpk2000** [comment]
I see, well I choose code to be a bit more readable to others who view it
```
#include<bits/stdc++.h>
using namespace std;
 
#if !defined(ONLINE_JUDGE)
#include "/home/ichigo/debug.hpp"
#define deb(x...) cerr << "[" << #x << "] = ["; _print(x)
#else
#define deb(x...)
#endif
 
#define fi first
#define se second
#define FIO {ios::sync_with_stdio(0);cin.tie(nullptr);cout.tie(nullptr);}
#define pb push_back
#define all(x) (x).begin(), (x).end()
#define rall(x) (x).rbegin(), (x).rend()
#define forn(i, n) for (int i = 0; i < (int)(n); ++i)
#define for1(i, n) for (int i = 1; i <= (int)(n); ++i)
#define ford(i, n) for (int i = (int)(n) - 1; i >= 0; --i)
 
typedef pair<int, int> pii;
typedef vector<int> vi;
typedef vector<pii> vpi;
typedef vector<vi> vvi;
typedef long long ll;
typedef vector<ll> vll;
typedef vector<vll> vvll;
typedef long double ld;


int main(){
	FIO
	

	return 0;
}
```
This is so minimal and not so heavily templatized but the readability is justified. Anyways i still need to see some of your templates code and modify mine :)

**Comment by ouuan** [comment]
So I won't use header files for my template, you can copy any part of my templates or modify anything to meet your need.
